// Concerto — Bellrock supplier portal  ->  VX Suite
//
// GENERATED by kernel/spec.mjs from a read-only survey of both systems, then
// left deliberately unfinished. What is filled in is what the surveys PROVED:
// the key, the state map, the leg order and the action recipes. What is left
// is what no survey can give you — the selectors, and the judgement about when
// to act. Fill those in; do not invent the ones above.
//
// 80% of the domain crosses cleanly between these two.
import SPEC from './spec.json' with { type: 'json' };

/** Their word -> ours -> their word. Straight out of the crosswalk. */
export const STATES = {
  "ATTENDED": {
    "concerto": "Attended",
    "vx": null
  },
  "IN_PROGRESS": {
    "concerto": "In progress",
    "vx": "In Progress"
  },
  "PAUSED": {
    "concerto": "Parts On Order",
    "vx": "Service Incomplete (by inference)"
  },
  "COMPLETED": {
    "concerto": "Work complete",
    "vx": "Service Complete / invoiced"
  },
  "AWAITING_EVIDENCE": {
    "concerto": "Awaiting Certificate (tile)",
    "vx": null
  },
  "AWAITING_CONTRACTOR": {
    "concerto": "Awaiting Acceptance (tile)",
    "vx": "Assigned / Pend. Accept"
  },
  "AWAITING_TRIAGE": {
    "concerto": null,
    "vx": "Pend."
  },
  "CANCELLED": {
    "concerto": null,
    "vx": "Cancelled / EOL"
  }
};
export const toCanonical = (system, word) =>
  Object.entries(STATES).find(([, v]) => (v[system] || '').toLowerCase() === String(word).toLowerCase())?.[0] || null;
export const fromCanonical = (system, canon) => STATES[canon]?.[system] || null;

/** The cross-system key. Nothing else may be used to match records. */
export const KEY = {
  "concerto": "Supplier's ref",
  "vx": "Contractor Reference No. · action: Set Provider Reference Number",
  "rule": "write each reference into the other system before any other write, then find records by searching it"
};

/**
 * A JOB ARRIVES — needs a rule
 * intake only crosses by inference (order emailed to the helpdesk mailbox, logged in the feed against Date/Time Created — found by polling, nothing announces it). Write the rule down, and test it against real jobs before trusting it.
 * Writes into: VX Suite
 * No write on this leg.
 */
export const intake = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('intake: not implemented');
};

/**
 * TIE THE TWO RECORDS TOGETHER — buildable
 * Every concept it depends on crosses cleanly.
 * Writes into: Concerto — Bellrock supplier portal
 * No write on this leg.
 */
export const key = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('key: not implemented');
};

/**
 * ACCEPTANCE — needs a rule
 * acceptance only crosses by inference (Date acknowledged · feed: Accept within SLA against status Pend. Accept + Date Assigned). Write the rule down, and test it against real jobs before trusting it. The action itself has not been seen yet — it is on a record in a state we have not opened.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: (only on an order Awaiting Acceptance — not yet captured)
 */
export const accept = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('accept: not implemented');
};

/**
 * A DATE IS PROMISED — buildable
 * Every concept it depends on crosses cleanly.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Add Appointment
 */
export const appointment = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('appointment: not implemented');
};

/**
 * SOMEBODY TURNED UP — blocked
 * attendance cannot be expressed on one side. Nothing to write to, so this leg has to live outside both systems — a mailbox, a store, or a person — until that changes.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Mark job as attended
 */
export const attend = async (job, ctx) => {
  // BLOCKED and not stubbed on purpose. attendance cannot be expressed on one side. Nothing to write to, so this leg has to live outside both systems — a mailbox, a store, or a person — until that changes.
  throw new Error('attend: not buildable against these two systems - see spec.json');
};

/**
 * THE JOB STOPS — needs a rule
 * pause only crosses by inference (status + action: Parts On Order against status: Service Incomplete). Write the rule down, and test it against real jobs before trusting it.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Parts On Order
 */
export const pause = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('pause: not implemented');
};

/**
 * THE PAPERWORK — blocked
 * evidence cannot be expressed on one side. Nothing to write to, so this leg has to live outside both systems — a mailbox, a store, or a person — until that changes.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Add Note/Document/Photo
 */
export const evidence = async (job, ctx) => {
  // BLOCKED and not stubbed on purpose. evidence cannot be expressed on one side. Nothing to write to, so this leg has to live outside both systems — a mailbox, a store, or a person — until that changes.
  throw new Error('evidence: not buildable against these two systems - see spec.json');
};

/**
 * THE JOB CLOSES — buildable
 * Every concept it depends on crosses cleanly.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Add Note/Document/Photo -> Work complete
 */
export const complete = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('complete: not implemented');
};

/**
 * SOMEBODY HAS TO BE CHASED — needs a rule
 * exception only crosses by inference (Currently with (cost referral only) against 1st/2nd Level Escalated By · Escalation Type · Escalation Comment). Write the rule down, and test it against real jobs before trusting it.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Add Note
 */
export const exception = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('exception: not implemented');
};

/**
 * QUOTES AND SPEND — buildable
 * Every concept it depends on crosses cleanly.
 * Writes into: Concerto — Bellrock supplier portal
 * Actions, in order: Quote required
 */
export const money = async (job, ctx) => {
  // TODO selectors. Everything else on this leg is already decided.
  throw new Error('money: not implemented');
};
