// Run the domain against every system we hold captures for, and write it down.
//
//   node kernel/report.mjs                 → terminal
//   node kernel/report.mjs --write          → also docs/kernel-report.md
//
// Adding a third system is one file in kernel/systems/ and a line here. That is
// the test: if the questions in domain.mjs only fit the two systems they were
// written beside, a third will show it immediately as a row of "not mapped".
import fs from 'node:fs';
import path from 'node:path';
import { CONCEPTS } from './domain.mjs';
import { discover, compare } from './discover.mjs';
import concerto from './systems/concerto.mjs';
import vx from './systems/vx.mjs';

const WRITE = process.argv.includes('--write');
const root = process.cwd();
const systems = [concerto, vx];
const runs = systems.map((s) => discover(s, { root }));

const MARK = { direct: '●', inferred: '◐', absent: '○' };
const pad = (s, n) => String(s).padEnd(n).slice(0, n);

for (const r of runs) {
  console.log(`\n\n  ${r.system.name}  —  ${r.score.pct}%  (${r.system.vendor})`);
  console.log(`  captures: ${r.captures}`);
  console.log(`  ${r.counts.stated} stated · ${r.counts.inferred} inferred · ${r.counts.unobserved} UNOBSERVED · ${r.counts.unproven} UNPROVEN · ${r.counts.contradicted} CONTRADICTED
`);
  for (const f of r.findings) {
    const flag = f.contradicted ? `   ⚠ CONTRADICTED — "${f.where.find}" appears in ${f.proof.file}`
      : f.status === 'unobserved' ? '   — unobserved: absence is not proven'
      : f.status === 'stated' || f.status === 'inferred' ? '' : `   ⚠ UNPROVEN (${f.proof.reason})`;
    const src = f.grade === 'absent' ? `searched ${f.proof.searched ?? 0} file(s)` : (f.proof.file || '');
    console.log(`   ${MARK[f.grade]} ${pad(f.id, 12)} ${pad(f.weight, 9)} ${src}${flag}`);
  }
  if (r.blockingGaps.length) {
    console.log(`\n   BLOCKING GAPS: ${r.blockingGaps.map((g) => g.id).join(', ')}`);
  }
}

const rows = compare(runs[0], runs[1]);
console.log(`\n\n  DIVERGENCE — where the two express the same fact differently\n`);
for (const c of rows.filter((x) => x.divergent)) {
  console.log(`   ${pad(c.id, 12)} ${pad(runs[0].system.id + ': ' + c.a.grade, 22)} ${runs[1].system.id}: ${c.b.grade}`);
}

if (WRITE) {
  const md = [];
  md.push('# The kernel report — one domain, read against every system we hold\n');
  md.push('Generated by `node kernel/report.mjs --write`. Every claim below points at a captured');
  md.push('file; any claim whose evidence does not resolve is marked **unproven** and scores nothing.\n');
  md.push('`●` stated · `◐` inferred · `○` absent\n');

  md.push('## Scores\n');
  md.push('| System | Vendor | Stated | Inferred | Unobserved | Unproven | Coverage |');
  md.push('|---|---|---|---|---|---|---|');
  for (const r of runs) {
    md.push(`| ${r.system.name} | ${r.system.vendor} | ${r.counts.stated} | ${r.counts.inferred} | ${r.counts.unobserved} | ${r.counts.unproven} | **${r.score.pct}%** |`);
  }
  md.push('\nCoverage is not a quality score for the software. It is how much of the domain the system');
  md.push('states outright rather than leaving to be inferred — which is exactly the work an operating');
  md.push('layer has to do on top of it.\n');

  md.push('## Side by side\n');
  md.push(`| | ${runs.map((r) => r.system.name).join(' | ')} |`);
  md.push('|---|' + runs.map(() => '---|').join(''));
  for (const c of CONCEPTS) {
    const cells = runs.map((r) => {
      const f = r.findings.find((x) => x.id === c.id);
      return `${MARK[f.grade]} ${f.proven ? '' : '⚠ '}${(f.how || '').replace(/\|/g, '\\|')}`;
    });
    md.push(`| **${c.id}**<br><span title="${c.question}">${c.question}</span> | ${cells.join(' | ')} |`);
  }

  md.push('\n## Where they diverge\n');
  for (const c of rows.filter((x) => x.divergent)) {
    md.push(`- **${c.id}** (${c.weight}) — ${runs[0].system.id}: *${c.a.grade}*; ${runs[1].system.id}: *${c.b.grade}*`);
  }

  md.push('\n## Evidence\n');
  for (const r of runs) {
    md.push(`### ${r.system.name}\n`);
    md.push('| Concept | Grade | Found in | Sample |');
    md.push('|---|---|---|---|');
    for (const f of r.findings) {
      const cell = f.contradicted ? '**contradicted** — found in `' + f.proof.file + '`'
        : f.status === 'unobserved' ? '**unobserved** — searched ' + (f.proof.searched ?? 0) + ' file(s) and did not see it, which is not proof it is absent'
        : f.proven ? '`' + f.proof.file + '`' : '**unproven** — ' + f.proof.reason;
      md.push(`| ${f.id} | ${f.grade} | ${cell} | ${(f.proof.sample || '').slice(0, 110).replace(/\|/g, '\\|')} |`);
    }
    md.push('');
  }
  const out = path.join(root, 'docs', 'kernel-report.md');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, md.join('\n') + '\n');
  console.log(`\n  written: ${out}\n`);
}
